#!/usr/bin/env bash
SECRETS_FILE=${1}
ONLY_SPECIFIED=${2}

INPUT_EXAMPLE="k8s-secrets-to-env <path/to/secrets>"

if test -z $SECRETS_FILE
then
    echo "PATH TO SECRETS FILE IS MISSING [$INPUT_EXAMPLE]"
    exit 1;
fi

mkdir -p ".generated/"

export RAND_TMP_ID="r_$(date +%Y%m%d%H%M%S)_$(( ( RANDOM % 10 )  + 1 ))"
sed -e '1,/stringData:/d;s/:[^:\/\/]/=/g;s/$//g;s/ *=/=/g;s/^[ \t]*//;s/[^=]\+/export &; &/;/^#/d;' $SECRETS_FILE > .generated/$RAND_TMP_ID.env

if ! test -z $ONLY_SPECIFIED
then
    grep -vf $ONLY_SPECIFIED myfile.txt
fi

printf "$(pwd)/.generated/$RAND_TMP_ID.env"
