#!/usr/bin/env bash
RUN_SOURCE=${1}

export RAND_TMP_ID="r_$(date +%Y%m%d%H%M%S)_$(( ( RANDOM % 10 )  + 1 ))"
sed -e '1,/stringData:/d;s/:[^:\/\/]/=/g;s/$//g;s/ *=/=/g;s/^[ \t]*//;s/[^=]\+/export &; &/;' secrets.yaml > .generated/$RAND_TMP_ID.env

set -a
source .generated/$RAND_TMP_ID.env
set +a

echo "$(pwd)/.generated/$RAND_TMP_ID.env created and sourced"
